# Generated by Django 3.1.4 on 2020-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='label',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
