# Generated by Django 3.1.4 on 2020-12-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0002_auto_20201201_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
