# Generated by Django 3.1.4 on 2020-12-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0003_auto_20201201_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='delete_kar_denge',
            field=models.IntegerField(default=10),
        ),
    ]
