# Generated by Django 3.1.4 on 2020-12-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0004_size_delete_kar_denge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='delete_kar_denge',
        ),
    ]
