# Generated by Django 3.1.4 on 2020-12-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_pizza', '0005_remove_size_delete_kar_denge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
